// <auto-generated />
using System;
using AnubusAutharizationStub;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnubusAutharizationStub.Database.Migrations
{
    [DbContext(typeof(AuthStubDbContext))]
    [Migration("20221006173836_Intial")]
    partial class Intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnubusAutharizationStub.UserStub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrgId")
                        .HasColumnType("bigint");

                    b.Property<int[]>("Roles")
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("UsersStub");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Login = "ЦА",
                            Name = "ЦА",
                            OrgId = 0L,
                            Roles = new[] { 1 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
